name: Build OCR Console App
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # This single command restores, builds, and publishes the app
    - name: Publish the application
      run: dotnet publish FoundryOcr.Cli.csproj -c Release -r win-x64 --self-contained true

    # The path is now simpler and points to the standard publish output
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ocr-tool
        path: bin/Release/net8.0-windows10.0.22621.0/win-x64/publish/
