name: Build OCR Console App
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # No change to setup steps
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x' # Make sure this matches your project's .NET version

    - name: Restore NuGet packages
      run: dotnet restore .\FoundryOcr.Cli.csproj

    # This is the corrected step
    - name: Publish the application
      run: dotnet publish .\FoundryOcr.Cli.csproj -c Release -r win-x64 --self-contained true

    # This step will now find the files
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ocr-tool
        path: bin\x64\Release\net6.0-windows10.0.22621.0\win-x64\publish\
