name: Build OCR Console App
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x' # Or your target .NET version

    # Add this step to install the required VS Build Tools
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: dotnet restore .\FoundryOcr.Cli.csproj

    - name: Publish the application
      run: dotnet publish .\FoundryOcr.Cli.csproj -c Release -r win-x64 --self-contained true

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ocr-tool
        path: bin\x64\Release\net6.0-windows10.0.22621.0\win-x64\publish\
