name: Build OCR Console App
on: [push]

jobs:
  build:
    # Use the standard Windows runner
    runs-on: windows-latest

    steps:
    # 1. Checkout your code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Set up the complete Visual Studio build environment. This is the key fix.
    #    It provides the missing build tasks like the one in the error.
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # 3. Set up a stable .NET 8 SDK, not a preview of .NET 9
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    # 4. Restore NuGet packages using MSBuild
    - name: Restore NuGet packages
      run: msbuild FoundryOcr.Cli.csproj -t:Restore -p:Configuration=Release

    # 5. Build and Publish the application using MSBuild
    - name: Build and Publish Application
      run: msbuild FoundryOcr.Cli.csproj -t:Publish -p:Configuration=Release -p:Platform=x64 -p:WindowsAppSDKSelfContained=true

    # 6. Upload the artifact from the correct publish location
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ocr-tool
        path: bin/x64/Release/net6.0-windows10.0.22621.0/win-x64/publish/
